AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.bundle/**/*'
    - 'node_modules/**/*'

# Style cops
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

# Metrics cops - adjust for real-world code
Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

# Layout cops
Layout/LineLength:
  Max: 120

# Lint cops for better type checking
Lint/UselessAssignment:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

# Naming cops
Naming/FileName:
  Exclude:
    - 'lib/sxn/CLI.rb'

# Security cops
Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true
