AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.bundle/**/*'
    - 'node_modules/**/*'

# Style cops
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

# Metrics cops - adjust for real-world code
Metrics/MethodLength:
  Max: 60

Metrics/ClassLength:
  Max: 700

Metrics/ModuleLength:
  Max: 500

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/AbcSize:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 40

Metrics/BlockNesting:
  Max: 5

# Layout cops
Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

# Lint cops for better type checking
Lint/UselessAssignment:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

# Allow shadowed exceptions for comprehensive error handling
Lint/ShadowedException:
  Enabled: false

# Allow duplicate branches for clarity
Lint/DuplicateBranch:
  Enabled: false

# Naming cops
Naming/FileName:
  Exclude:
    - 'lib/sxn/CLI.rb'

# Security cops
Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

# Gemspec cops
Gemspec/DevelopmentDependencies:
  Enabled: false

# Style cops - allow predicates
Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

# Allow OpenStruct for flexibility
Style/OpenStructUse:
  Enabled: false

# Allow multiline block chains for testing
Style/MultilineBlockChain:
  Enabled: false

# Allow case statements that could be hashes
Style/HashLikeCase:
  Enabled: false

# Allow parameter lists for complex initializers
Metrics/ParameterLists:
  Max: 8
  Exclude:
    - 'lib/sxn/rules/base_rule.rb'
    - 'lib/sxn/rules/copy_files_rule.rb'
    - 'lib/sxn/rules/setup_commands_rule.rb'
    - 'lib/sxn/rules/template_rule.rb'

# Naming cops - allow set_ methods
Naming/AccessorMethodName:
  Enabled: false
