name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems

    - name: Run RSpec tests
      run: |
        bundle exec rspec --exclude-pattern "**/comprehensive*_spec.rb" --format documentation

    - name: Run RuboCop
      run: |
        bundle exec rubocop --parallel

  typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Install Steep
      run: |
        gem install steep

    - name: Run Steep type checking
      run: |
        steep check || true # Allow failures for now as we improve type coverage
      continue-on-error: true

  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Run tests with coverage
      env:
        ENABLE_SIMPLECOV: true
      run: |
        bundle exec rspec --exclude-pattern "**/comprehensive*_spec.rb"

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/